DROP DATABASE IF EXISTS krautundrueben;
CREATE DATABASE IF NOT EXISTS krautundrueben;
USE krautundrueben;


CREATE TABLE KUNDE (
    KUNDENNR        INTEGER NOT NULL AUTO_INCREMENT,
    NACHNAME        VARCHAR(50),
    VORNAME         VARCHAR(50),
    GEBURTSDATUM	DATE,
    PASSWORT        VARCHAR(255),
	STRASSE         VARCHAR(50),
	HAUSNR			VARCHAR(6),
    PLZ             VARCHAR(5),
    ORT             VARCHAR(50),
    TELEFON         VARCHAR(25),
    EMAIL           VARCHAR(50) UNIQUE,
    PRIMARY KEY (KUNDENNR)
);

CREATE TABLE ZUTAT(
    ZUTATENNR			INTEGER NOT NULL,
    BEZEICHNUNG         VARCHAR(50),
    EINHEIT        	    VARCHAR (25),
    NETTOPREIS          DECIMAL(10,2),
    BESTAND             INTEGER,
    LIEFERANT			INTEGER,
	KALORIEN			INTEGER,
	KOHLENHYDRATE		DECIMAL (10,2),
	PROTEIN				DECIMAL(10,2),
    PRIMARY KEY (ZUTATENNR)
);

CREATE TABLE BESTELLUNG (
    BESTELLNR        INTEGER AUTO_INCREMENT NOT NULL,
    KUNDENNR         INTEGER,
    BESTELLDATUM     DATE,
    RECHNUNGSBETRAG  DECIMAL(10,2),
    PRIMARY KEY (BESTELLNR)
);

CREATE TABLE BESTELLUNGZUTAT (
    BESTELLNR       INTEGER NOT NULL,
    ZUTATENNR       INTEGER,
    MENGE     		INTEGER
);

CREATE TABLE LIEFERANT (
    LIEFERANTENNR   INTEGER NOT NULL,
    LIEFERANTENNAME VARCHAR(50),
    STRASSE         VARCHAR(50),
    HAUSNR			VARCHAR(6),
    PLZ             VARCHAR(5),
    ORT             VARCHAR(50),
    TELEFON			VARCHAR(25),
    EMAIL           VARCHAR(50),
    PRIMARY KEY (LIEFERANTENNR)
);

CREATE TABLE REZEPTE (
    REZEPTNR INTEGER NOT NULL,
    REZEPTNAME VARCHAR(50),
    REZEPTLINK VARCHAR(250),
    REZEPTZUTATENANZAHL INTEGER,
    PRIMARY KEY (REZEPTNR)
);

CREATE TABLE REZEPTEZUTAT (
    REZEPTNR INTEGER NOT NULL,
    ZUTATENNR INTEGER NOT NULL,
    MENGE DECIMAL(10,2),
    FOREIGN KEY (REZEPTNR) REFERENCES REZEPTE(REZEPTNR),
    FOREIGN KEY (ZUTATENNR) REFERENCES ZUTAT(ZUTATENNR)
);

CREATE TABLE DIET (
    DIETNR INTEGER NOT NULL,
    DIETNAME VARCHAR(50),
    PRIMARY KEY (DIETNR)
);

CREATE TABLE DIETREZEPTE (
    DIETNR INTEGER NOT NULL,
    REZEPTNR INTEGER NOT NULL,
    FOREIGN KEY (DIETNR) REFERENCES DIET (DIETNR),
    FOREIGN KEY (REZEPTNR) REFERENCES REZEPTE (REZEPTNR)
);

CREATE TABLE DIETZUTAT (
    DIETNR INTEGER NOT NULL,
    ZUTATENNR INTEGER NOT NULL,
    FOREIGN KEY (DIETNR) REFERENCES DIET (DIETNR),
    FOREIGN KEY (ZUTATENNR) REFERENCES ZUTAT (ZUTATENNR)
);

CREATE TABLE ALLERGIE (
    ALLERGIENR INTEGER NOT NULL,
    ALLERGIENAME VARCHAR(50),
    PRIMARY KEY (ALLERGIENR)
);

CREATE TABLE ALLERGIEREZEPTE (
    ALLERGIENR INTEGER NOT NULL,
    REZEPTNR INTEGER NOT NULL,
    FOREIGN KEY (ALLERGIENR) REFERENCES ALLERGIE (ALLERGIENR),
    FOREIGN KEY (REZEPTNR) REFERENCES REZEPTE (REZEPTNR)
);

CREATE TABLE ALLERGIEZUTAT (
    ALLERGIENR INTEGER NOT NULL,
    ZUTATENNR INTEGER NOT NULL,
    FOREIGN KEY (ALLERGIENR) REFERENCES ALLERGIE (ALLERGIENR),
    FOREIGN KEY (ZUTATENNR) REFERENCES ZUTAT (ZUTATENNR)
);


CREATE TABLE KUNDEALLERGIE (
    KUNDENNR        INTEGER NOT NULL,
    ALLERGIENR      INTEGER,
    FOREIGN KEY (KUNDENNR) REFERENCES KUNDE (KUNDENNR),
    FOREIGN KEY (ALLERGIENR) REFERENCES ALLERGIE (ALLERGIENR),
    CONSTRAINT ONCE UNIQUE (KUNDENNR, ALLERGIENR)
);

CREATE TABLE KUNDEDIET (
    KUNDENNR        INTEGER NOT NULL,
    DIETNR          INTEGER,
    FOREIGN KEY (KUNDENNR) REFERENCES KUNDE (KUNDENNR),
    FOREIGN KEY (DIETNR) REFERENCES DIET (DIETNR),
    CONSTRAINT ONCE UNIQUE (KUNDENNR, DIETNR)
);

ALTER TABLE BESTELLUNGZUTAT ADD PRIMARY KEY (BESTELLNR,ZUTATENNR);
ALTER TABLE DIETREZEPTE ADD PRIMARY KEY (DIETNR,REZEPTNR);
ALTER TABLE DIETZUTAT ADD PRIMARY KEY (DIETNR,ZUTATENNR);
ALTER TABLE ALLERGIEREZEPTE ADD PRIMARY KEY (ALLERGIENR,REZEPTNR);
ALTER TABLE ALLERGIEZUTAT ADD PRIMARY KEY (ALLERGIENR,ZUTATENNR);
ALTER TABLE REZEPTEZUTAT ADD PRIMARY KEY (REZEPTNR,ZUTATENNR);

/******************************************************************************/
/***                              Foreign Keys                              ***/
/******************************************************************************/

ALTER TABLE ZUTAT ADD FOREIGN KEY (LIEFERANT) REFERENCES LIEFERANT (LIEFERANTENNR);
ALTER TABLE BESTELLUNGZUTAT ADD FOREIGN KEY (BESTELLNR) REFERENCES BESTELLUNG (BESTELLNR);
ALTER TABLE BESTELLUNG ADD FOREIGN KEY (KUNDENNR) REFERENCES KUNDE (KUNDENNR);
ALTER TABLE BESTELLUNGZUTAT ADD FOREIGN KEY (ZUTATENNR) REFERENCES ZUTAT (ZUTATENNR);
